server:
  port: 8989

# DataSource Config
spring:
  datasource:
    name: fendo
    url: jdbc:mysql://192.168.100.19:3306/training?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /*
  #配置上传文件大小 maxFileSize是单个文件大小  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #不要为我们工程中的资源文件建立映射,加上此配置，404错误能够封装，但是swagger访问不了
  #  resources:
  #    add-mappings: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.deluxe: debug

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  #type-aliases-package:
  #项目启动会检查xml配置存在(只在开发时候打开)
  check-config-location: true
  # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
  map-underscore-to-camel-case: true
  configuration:
    jdbc-type-for-null: 'null' #可以更新为空值




doctor:
  xiaoe_id: p_5cadae920ea2e_adAM9Zyl
  type: 4
  temp_code: SMS_168826961
  course_name: 人人必学的家庭健康课
  source: PAHYS
  ips: 127.0.0.1
remote:
  send_course_url: http://localhost:8580/play/send_course.do
